DROP TABLE IF EXISTS dbo.svRoles;
DROP PROCEDURE IF EXISTS dbo.svGetRoles;
DROP PROCEDURE IF EXISTS dbo.svGetRoleById;
DROP PROCEDURE IF EXISTS dbo.svGetRoleByName;
DROP PROCEDURE IF EXISTS dbo.svGetRoleDeleteById;
DROP PROCeDURE IF EXISTS dbo.svUpdRolePerformer;