DROP TABLE IF EXISTS dbo.svRoles;
DROP PROCEDURE IF EXISTS dbo.svAllRoles;
DROP PROCEDURE IF EXISTS dbo.svGetRoleById;
DROP PROCEDURE IF EXISTS dbo.svGetRoleByName;
DROP PROCEDURE IF EXISTS dbo.svDelRoleById;
DROP PROCeDURE IF EXISTS dbo.svUpdRolePerformer;