DROP TABLE dbo.svPerformers;
DROP PROCEDURE dbo.svPerformerAll;
DROP PROCEDURE dbo.svPerformerAuth;
DROP PROCEDURE dbo.svPerformerFindById;
DROP PROCEDURE dbo.svPerformerUpdById;
DROP PROCEDURE dbo.svPerformerExistsById;
DROP PROCEDURE dbo.svPerformersCount;
DROP PROCEDURE dbo.dbo.svPerformersPagination;
DROP PROCEDURE dbo.dbo.svPerformerFilterById;