DROP TABLE IF EXISTS svTB_Oper;
DROP PROCEDURE IF EXISTS svTB_AllOper;
DROP PROCEDURE IF EXISTS svTB_GetOperByName;
DROP PROCEDURE IF EXISTS svTB_GetOperById;
DROP PROCEDURE IF EXISTS svTB_AddOper;
DROP PROCEDURE IF EXISTS svTB_UpdOper;
DROP PROCEDURE IF EXISTS svTB_DelOperById;